### ISSUE TITLE
記録が残ると嬉しいな

### ISSUE THREAD

**Issue by bleu48** [nodchip/TanukiColiseum#1]
対局設定や対戦結果を保存したり再度読み込んだり出来れば部分的な変更で再戦したりするのに便利です。
また，WebなどにUpする際も画像ではない方が利用しやすいと思いますのでテキスト形式の保存なども有用かと思います。

加えて例外的かもしれませんが，戦型分類などを事後行うことを考えればフォルダなどを作成し棋譜を残すようなオプションもあると助かります。

**Comment by nodchip** [comment]
要望ありがとうございます。対応させていただきたいと思います。

**Comment by nodchip** [comment]
https://github.com/nodchip/TanukiColiseum/commit/d112beefce2f01e12acf6ff11cb392d5340afbec にて対応させていただきました。
