### ISSUE TITLE
GUI画面から測定開始できない

### ISSUE THREAD

**Issue by mizar** [nodchip/TanukiColiseum#11]
https://github.com/nodchip/TanukiColiseum/blob/master/TanukiColiseum/MainModel.cs#L115

固定文字列 `"TanukiColiseum.setting.xml"` のディレクトリを作成しようとしているようですが、この文字列からではディレクトリ名が含まれていないため、ディレクトリの作成に失敗して測定開始時に例外エラーが発生するようです。

**Comment by nodchip** [comment]
ご報告いただきありがとうございます。のちほど修正いたします。
