### ISSUE TITLE
残り物理メモリ量

### ISSUE THREAD

**Issue by yaneurao** [nodchip/TanukiColiseum#13]
halfKPE9、評価関数だけで600MB程度消費するのですけど、皆さん、tournamentビルドで棋力計測されているようです。そうすると、EvalHashが1024がデフォルト値なので、USI_Hash 128MBだとしても、エンジン本体が2GBほど消費します。

これを3990Xで1スレッド128並列で対局させるとエンジンだけで128*2*2 = 512GB必要でOSやら何やらで530GBぐらいのメモリがないといけないことになります。

3990Xが普通になってきたこの時代、わりと簡単に上のように棋力計測で物理メモリをうっかり使い切ってしまうことは珍しくもなく、論理スレッド数いっぱいまで使っているとタスクマネージャーを開くのもままならないので、物理メモリが残り何%であるかぐらいは表示があってほしい気はします。(残り少ないときは、それが赤い文字になるとかも)

**Comment by nodchip** [comment]
要望ありがとうございます。表示より、残りメモリが足りない場合にエンジンを起動しない、という実装のほうが安全かもしれません。エンジン起動時、残りメモリが少ない場合に、警告を表示して対局を中止する、という形で実装したいと思います。

**Comment by yaneurao** [comment]
おお、それが良いですね😊

**Comment by nodchip** [comment]
https://github.com/nodchip/TanukiColiseum/commit/7d621fbbbb1c51522527b92e15c7dd020062f97d で対応いたしました。
