### ISSUE TITLE
引き分けにする手数

### ISSUE THREAD

**Issue by komafont** [nodchip/TanukiColiseum#19]
たぬころ内では、Engine.csにて、`private const int MaxMoves = 320;` と定義する一方、
エンジン側には、Coliseum.csにて、`{"MaxMovesToDraw", "256"}` を送っているため、
256手目付近からの挙動に問題が起こるようです。

一旦、どちらか（個人的には320手が好み）で統一した上で、
機会があれば、MaxMovesToDrawとResignValueを、ユーザー側で設定できるようにしてはいかがでしょうか。

**Comment by komafont** [comment]
下記、2020-12-10 https://github.com/nodchip/TanukiColiseum/commit/42e5c3d8776d8f6bba519eae8deeb49ac9a48b9b のバージョンで生成されたsfenとなります。

詰ますことも千日手判定されることもなく続いていますので、ご参考までに。

エンジン: YaneuraOu-v6.0.0, 評価関数1: qoa, 評価関数2: elmo2020
> startpos moves 7g7f 8c8d 2g2f 8d8e 8h7g 3c3d 7i8h 4a3b 6i7h 4c4d 2f2e 2b3c 3i4h 3a4b 7g6h 4b4c 5i6i 7c7d 3g3f 7a6b 4i5h 6a5b 9g9f 8a7c 5g5f 5a4a 1g1f 1c1d 2i3g 9c9d 6g6f 5c5d 7h6g 3c4b 6i7h 8e8f 8g8f 4b8f 8i7g 8f4b P*8g 8b8a 4g4f 4a3a 4h4g 6b5c 6h5g 6c6d 2h2i 4b5a 5h6h 5a4b 7h8i 3a2b 8i7h 2b3a 7h8i 3a2b 6h7h 2b3a 2i2h 3a2b 2h2i 2b3a 4g5h 3a2b 5h4g 2b3a 4g5h 3a2b 5h4g 2b3a 4g5h 3a2b 5h4g 2b3a 4g5h 3a2b 5h4g 2b3a 2i2h 3a2b 2h2i 2b3a 1i1h 3a2b 2i2h 9a9b 2h2i 2b3a 2i2h 3a2b 2h2i 2b3a 2i2h 3a2b 2h2i 2b3a 2i2h 3a2b 2h2i 2b3a 4g5h 3a2b 5h4g 2b3a 4g5h 4b5a 5h4g 5a4b 2i2h 3a2b 2h2i 2b3a 4g5h 4b5a 5h4g 5a4b 4g5h 4b5a 5h4g 5a4b 4g5h 4b5a 5h4g 5a4b 2i2h 3a2b 2h2i 2b3a 4g5h 4b5a 5h4g 5a4b 2i4i 3a2b 4i2i 2b3a 4g5h 4b5a 5h4g 5a4b 2i2h 3a2b 2h2i 2b3a 4g5h 4b5a 5h4g 5a4b 2i2h 3a2b 2h2i 2b3a 4g5h 4b5a 5h4g 5a4b 2i4i 3a2b 4i2i 2b3a 4g5h 4b5a 5h4g 5a4b 2i4i 3a2b 4i1i 9d9e 9f9e 7d7e 1f1e 1d1e 7f7e 6d6e 6f6e P*6d 2e2d 2c2d P*2e P*9g 9i9g 7c6e 7g6e 6d6e 2e2d P*2g 1h1e P*1d 1e1d 1a1d P*1e 2g2h+ 1i1g N*6f 7h7g L*2f N*1i 2h2g 1i2g 9b9e 9g9e P*1f 1g1f 2f2g+ 9e9b+ 2g3g 9b8a 3g4g L*2c 2b3c 5g7i 4g4f 7i4f 4d4e 4f5g 6f5h+ 5g3i N*8e 2c2a+ N*9g 8h9g 8e9g+ R*1c 3c4d 3i1g 3d3e 7g7h S*9h 8i7i S*8i 1g3e 4d3d 6g7g 4e4f L*6i 5c4d 1c1d+ 5h5g 6i6h 8i7h+ 7i7h P*8f 2d2c+ 3d4e N*3g 4e5f S*6g 5g6g 7g6g 5f4g L*4i 4g5h 2c3b 4f4g+ 7e7d 5d5e 7d7c+ 5e5f 8g8f 5f5g+ 8f8e 6e6f 8e8d 6f6g+ 6h6g 4c3b 8d8c+ 3b2a 4i4g 2a1b 4g4d 1b1c 4d4b+ 1c1d 1e1d 9h8g+ 7h8i 5b4b 1d1c+ 4b3b 6g6a+ 3b2b 3g2e 2b1b 2e3c+ 1b1a 1f1d 1a1b 1d1e 1b1a 1e1d 1a1b 1d1e 1b1a 1e1d 1a1b 1d1e 1b1a 1e1d 1a1b 1d1e 1b1a 1e1d 1a1b 1d1e 1b1a 1e1d 1a1b 1d1e 1b1a 1e1d 1a1b 1d1e 1b1a 1e1d 1a1b 1d1e 1b1a

**Comment by nodchip** [comment]
ご報告ありがとうございます。後ほど対応いたします。

**Comment by nodchip** [comment]
https://github.com/nodchip/TanukiColiseum/commit/d4b23dc648224ff6322d989f724856171f221222 で修正いたしました。ご確認いただければ幸いです。

千日手判定は https://github.com/nodchip/TanukiColiseum/issues/20 で対応したいと思います。

**Comment by komafont** [comment]
早速のご対応ありがとうございます。
長手数の対局が増える条件でも、より安心して利用させていただきます。
