### ISSUE TITLE
開始局面ファイルパスが見つからないと、開始ボタンを押した時に何も反応が無い

### ISSUE THREAD

**Issue by mizar** [nodchip/TanukiColiseum#2]
![image](https://user-images.githubusercontent.com/68691/98235979-f2e39c80-1fa5-11eb-8afb-a846171facfc.png)

デバッグモードで動作させた場合は上記のような例外ウィンドウが出ますが、
そうでない場合は対局が何時までも始まらず、エラーメッセージも出ないような状態に陥るようです。

可能なら、例外エラーをハンドルして何らかの応答をした方が良いかもしれません。

**Comment by nodchip** [comment]
https://github.com/nodchip/TanukiColiseum/commit/751f1da841a34ad0bb25c86379fb567853269fb9 で対応させていただきました。
