### ISSUE TITLE
対局結果にエンジン名と、EVAL名の出力が欲しい

### ISSUE THREAD

**Issue by yaneurao** [nodchip/TanukiColiseum#3]
TANUKICOLISEUM、exeパスと評価関数フォルダパス、末尾しか出てないので何と何を戦わせてるのかすらわかりません:disappointed_relieved: 

対局結果に、エンジンに対してusiコマンドを投げた時に返ってきたエンジン名と、EVAL名の出力が欲しい感じです。

**Comment by nodchip** [comment]
要望ありがとうございます。後ほど対応させていただきたいと思います。

**Comment by nodchip** [comment]
エンジン名につきましては https://github.com/nodchip/TanukiColiseum/commit/866c8018bfb9fa6409821fe24c91c624056ca5b2 で対応させていただきました。

やねうら王からEVAL名を取得する方法が見つからなかったため、そちらのほうは未対応となっております。

本Issueは一旦閉じさせていただきます。EVALについてはまた別途Issueを作成していただければと思います。
