### ISSUE TITLE
エンジンオプションThreadIdOffsetが適切に設定されてほしい

### ISSUE THREAD

**Issue by yaneurao** [nodchip/TanukiColiseum#4]
3990Xでの計測、ThreadIdOffsetをそれぞれのエンジンに対して適切に(PC全体として見たときのエンジンのスレッド番号みたいなのを)設定してやらなければならないと思うんですけど、この処理いりますね。

// やねうら王系とそうでないものとを戦わすことを考えると、エンジン選択の時に「やねうら王系」のチェックボックスもいる感じですかね。

**Comment by nodchip** [comment]
要望ありがとうございます。簡単のため、現時点では計測対象は全てやねうら王系を仮定したいと思います。後ほど対応させていただきます。

**Comment by nodchip** [comment]
https://github.com/nodchip/TanukiColiseum/commit/0c21722e7a87f1b7fc40b48a651909459eb47150 で対応させていただきました。
