### ISSUE TITLE
綴り難しすぎ

### ISSUE THREAD

**Issue by yaneurao** [nodchip/TanukiColiseum#6]
単語書き取り帳に1000回ぐらい書いてもcoliseumが綴れるようになる気が全くしません。

Colosseumのほうはかろうじて綴れます。普通、ローマ帝国時代のコロセウム(円形大演技場)は、後者の単語で綴るほうが多いように思います。

それで、いまさら名前を変更してほしいということではなく、愛称をつけてあげると良いのではないでしょうか。

私がつけて差し上げましょう。(勝手に)

愛称は、「たぬこ」です。

とっても可愛いですね！😍

**Comment by nodchip** [comment]
要望ありがとうございます。のちほど何らかの形で対応させていただきたいと思います。

**Comment by nodchip** [comment]
README.mdを更新いたしました。本Issueを閉じさせていただきたいと思います。
