### ISSUE TITLE
isreadyを2回目以降の対局で送っていない

### ISSUE THREAD

**Issue by yaneurao** [nodchip/TanukiColiseum#7]
isreadyを送らないとやねうら王系では置換表がクリアされないので対局を繰り返すうちに置換表が汚れて、それのせいで弱くなるです😥

**Comment by nodchip** [comment]
ご報告ありがとうございます。後ほど対応させていただきたいと思います。

**Comment by nodchip** [comment]
https://github.com/nodchip/TanukiColiseum/commit/40dd4e057d084668d7e1f890f7bbb7cfc22e3607 で対応させていただきました。
