### ISSUE TITLE
LargePageを使わない

### ISSUE THREAD

**Issue by yaneurao** [nodchip/TanukiColiseum#8]
LargePage対応について、これをエンジンオプションでオフにできないと、自己対局のときに片側のエンジンだけLargePageを使うことがあって、不公平なのでエンジンオプションでオフにできるようにとの要望を、やねうら王のブログのコメントで頂戴致しました。

まあ、自己対局のときはオフにしておくのが無難かなと思いました。それで、↓のようにその機能を追加したので、やねうら王系のエンジンの場合、このオプションをfalseに設定していただけないでしょうか。
https://github.com/yaneurao/YaneuraOu/commit/24613c705269ef70411486179947ca61275f590a

**Comment by nodchip** [comment]
承知いたしました。後ほど対応させていただきたいと思います。
